# Generated by Django 3.0.7 on 2020-06-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='isSpecialOffer',
            new_name='offer',
        ),
    ]
